function overrides = mvdr_config_real_signal_dcbias_4k()
%% ============== Experiment Override: Real Signal + 4kHz Interference ==============
% Matches the current real-signal baseline and keeps it as the default experiment.

overrides = struct();
overrides.experiment_name = 'real_signal_dcbias_4k';
% Use the real-signal audio files (example paths shown in README_REAL_SIGNAL.md)
overrides.target_audio = '../data/audio/Loosen1_60.wav';
overrides.interf_audio = '../data/audio/sine_wave_4k.wav';
overrides.output_dir = '../output/real_signal';
overrides.figure_subdir = 'figures';

overrides.plot_style = struct();
overrides.plot_style.figure_bg = 'white';
overrides.plot_style.axes_bg = 'white';
overrides.plot_style.text_color = 'k';
overrides.plot_style.colormap_name = 'turbo';
overrides.plot_style.use_invert_hardcopy = false;
overrides.plot_style.line_width = struct('main', 1.5, 'medium', 2.0, 'thick', 2.5, 'thin', 1.2);
overrides.plot_style.marker_size = struct('main', 8, 'detail', 10);
overrides.plot_style.font_sz = struct(...
	'title', 30, ...
	'subtitle', 29, ...
	'label', 29, ...
	'subtile_title', 29, ...
	'legend', 28, ...
	'tick', 28, ...
	'small_tick', 27, ...
	'colorbar', 28, ...
	'colorbar_label', 28);

% Legend labels for real-signal diagnostics (used by diagnostics module if wired)
overrides.legend_mvdr = {'Target-steered', 'Interference-steered'};
overrides.legend_psd = {'Target-steered', 'Interference-steered'};

% Eigenvalue plot display names for figure 215 (DisplayName entries)
overrides.eigen_plot_names = {'4kHz only', 'Full-band'};

overrides.figure213_annotations = struct();
overrides.figure213_annotations.mixed = struct( ...
	'text', 'DCBias+4kHz', ...
	'font_size', 15, ...
	'color', 'w', ...
	'font_weight', 'bold', ...
	'background_color', [0 0 0 0.5]);
overrides.figure213_annotations.target = struct( ...
	'text', 'Suppress 4kHz', ...
	'font_size', 15, ...
	'color', 'w', ...
	'font_weight', 'bold', ...
	'background_color', [0 0.5 0 0.5]);
overrides.figure213_annotations.interference = struct( ...
	'text', 'Suppress DCBias', ...
	'font_size', 15, ...
	'color', 'w', ...
	'font_weight', 'bold', ...
	'background_color', [0.5 0 0 0.5]);

end
