function overrides = mvdr_config_demo_2k_4k()
%% ============== Experiment Override: Demo 2kHz + 4kHz ==============
% Example experiment where the target is 2 kHz and the interferer is 4 kHz.

overrides = struct();
overrides.experiment_name = 'demo_2k_4k';
overrides.target_audio = '../data/audio/sine_wave_2k.wav';
overrides.interf_audio = '../data/audio/sine_wave_4k.wav';
overrides.output_dir = '../output/demo_2k_4k';
overrides.figure_subdir = 'figures';
overrides.plot_style = struct();
overrides.plot_style.figure_bg = 'white';
overrides.plot_style.axes_bg = 'white';
overrides.plot_style.text_color = 'k';
overrides.plot_style.colormap_name = 'turbo';
overrides.plot_style.use_invert_hardcopy = false;
overrides.plot_style.line_width = struct('main', 1.4, 'medium', 1.9, 'thick', 2.3, 'thin', 1.1);
overrides.plot_style.marker_size = struct('main', 7, 'detail', 9);
overrides.plot_style.font_sz = struct(...
	'title', 31, ...
	'subtitle', 30, ...
	'label', 30, ...
	'subtile_title', 30, ...
	'legend', 29, ...
	'tick', 29, ...
	'small_tick', 28, ...
	'colorbar', 29, ...
	'colorbar_label', 29);

overrides.legend_mvdr = {'2kHz-steered', '4kHz-steered'};
overrides.legend_psd = {'2kHz-steered', '4kHz-steered'};
overrides.eigen_plot_names = {'2kHz only', 'Full-band (2k+4k)'};

overrides.figure213_annotations = struct();
overrides.figure213_annotations.mixed = struct( ...
	'text', '2kHz+4kHz', ...
	'font_size', 15, ...
	'color', 'w', ...
	'font_weight', 'bold', ...
	'background_color', [0 0 0 0.5]);
overrides.figure213_annotations.target = struct( ...
	'text', 'Suppress 4kHz', ...
	'font_size', 15, ...
	'color', 'w', ...
	'font_weight', 'bold', ...
	'background_color', [0 0.5 0 0.5]);
overrides.figure213_annotations.interference = struct( ...
	'text', 'Suppress 2kHz', ...
	'font_size', 15, ...
	'color', 'w', ...
	'font_weight', 'bold', ...
	'background_color', [0.5 0 0 0.5]);

end
